version: "3"

services:
  consul:
#    command: -agent --dev
#    command: -server -bootstrap -rejoin
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  micro:
    command: --registry_address=consul:8500 api --handler=rpc
    image: microhq/micro:latest
    environment:
      - MICRO_REGISTRY=consul
    depends_on:
      - consul
      - api
    ports:
      - "8080:8080"
  api:
    build: ./api/hotel
    command: --registry_address=consul:8500
    environment:
      - MICRO_REGISTRY=consul
    depends_on:
      - consul
      - auth
      - geo
      - profile
      - rate
  auth:
    build: ./srv/auth
    environment:
      - MICRO_REGISTRY=consul
    command: --registry_address=consul:8500
    depends_on:
      - consul
  geo:
    build: ./srv/geo
    environment:
      - MICRO_REGISTRY=consul
    command: --registry_address=consul:8500
    depends_on:
      - consul
  profile:
    build: ./srv/profile
    environment:
      - MICRO_REGISTRY=consul
    command: --registry_address=consul:8500
    depends_on:
      - consul
  rate:
    build: ./srv/rate
    environment:
      - MICRO_REGISTRY=consul
    command: --registry_address=consul:8500
    depends_on:
      - consul
