version: "3"

services:
  consul:
#    command: -agent --dev
#    command: -server -bootstrap -rejoin
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  micro:
    command: --registry_address=consul:8500 api --handler=rpc
    image: microhq/micro:latest
    environment:
      - MICRO_REGISTRY=consul
    depends_on:
      - consul
      - api
    ports:
      - "8080:8080"
